# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 042249a5167e1c6d1e6504834a6da36df378ccbb52eb5f14187352325915bd2a05497901e767a2653981784dd9d8d2f165d95553cc1db3a8729c128736a68d4e

test:
  secret_key_base: 5023d06404c443d6a68a5ceee686d86cacd8a41913379460168293aab30085b8711490476a869117a68eee13bc150b9fead9041439d183592578a12a838fa8f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
